version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - db_agenda:/var/lib/mysql

volumes:
  db_agenda: